name: vm-nightly-test
'on':
  push:
    paths-ignore:
      - packages/account/**
      - packages/block/**
      - packages/blockchain/**
      - packages/common/**
      - packages/tx/**
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - run: npm install
        working-directory: '${{ env.cwd }}'
      - run: npm run testAPI
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
      - run: 'npm run testAPI:browser'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-state:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hardfork:
          - Byzantium
          - Constantinople
          - Petersburg
          - Istanbul
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - run: npm install
        working-directory: '${{ env.cwd }}'
      - name: 'Run ${{ matrix.hardfork }} state tests'
        run: 'npm run ${{ format(''testState{0}'', matrix.hardfork) }}'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-blockchain:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hardfork:
          - ''
          - Petersburg
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - run: npm install
        working-directory: '${{ env.cwd }}'
      - name: 'Run ${{ matrix.hardfork }} blockchain state tests'
        run: 'npm run ${{ format(''testBlockchain{0}'', matrix.hardfork) }}'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
