
# This whole file is a workaround, as Codecov does not fully support GitHub Actions for pull requests from external repositories.
# 

version: 2.1

aliases:
  - &config
    docker:
      - image: circleci/node:10

  - &coverage_steps
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: cd ~/project/packages/${CIRCLE_JOB} && npm install
      - run: 
          name: Running coverage tests
          command: cd ~/project/packages/${CIRCLE_JOB} && npm run coverage
      - run: 
          name: debug coverage test
          command: cat ~/project/packages/${CIRCLE_JOB}/coverage/lcov.info
      - run: 
          name: Codecov manual upload
          command: curl -s https://codecov.io/bash | bash -s -- -f ~/project/packages/${CIRCLE_JOB}/coverage/lcov.info -F ${CIRCLE_JOB} \
                        -t ${CODECOV_TOKEN} \
                        -n ${CIRCLE_BUILD_NUM} \
                        -y ".codecov.yml" \
                        -Z || echo 'Codecov upload failed'

jobs:
  account:
    <<: *config
    <<: *coverage_steps
  block:
    <<: *config
    <<: *coverage_steps
  blockchain:
    <<: *config
    <<: *coverage_steps
  common:
    <<: *config
    <<: *coverage_steps
  tx:
    <<: *config
    <<: *coverage_steps
  vm:
    <<: *config
    <<: *coverage_steps



workflows:
  version: 2
  coverage:
    jobs:
      - account
      - block
      - blockchain
      - common
      - tx
      - vm