version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

aliases:
  - &config
    docker:
      - image: circleci/node:10

  - &coverage_steps
    steps:
      - checkout
      - run: echo "Running job $CIRCLE_JOB"
      # - restore_cache:
      #     name: Restore node_modules cache
      #     keys:
      #       - node10-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      #       - node10-{{ .Environment.CIRCLE_JOB }}
      - run: 
          name: Installing dependencies
          command: cd ~/project/packages/$CIRCLE_JOB && npm install
      - run: 
          name: Running coverage tests
          command: cd ~/project/packages/$CIRCLE_JOB && npm run coverage
      - codecov/upload:
          file: ~/project/packages/$CIRCLE_JOB/coverage/lcov.info
          flags: $CIRCLE_JOB

jobs:
  account:
    <<: *config
    <<: *coverage_steps
  block:
    <<: *config
    <<: *coverage_steps
  blockchain:
    <<: *config
    <<: *coverage_steps
  common:
    <<: *config
    <<: *coverage_steps
  tx:
    <<: *config
    <<: *coverage_steps
  vm:
    <<: *config
    <<: *coverage_steps



workflows:
  version: 2
  coverage:
    jobs:
      - account
      - block
      - blockchain
      - common
      - tx
      - vm