name: vm-test
on: [push, pull_request]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/checkout@v1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node8-${{ hashFiles('**/package.json') }}

      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: npm run testAPI
        env:
          CI: true

      - run: npm run testAPI:browser
        env:
          CI: true

  test-state:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hardfork: ['Byzantium', 'Constantinople', 'Petersburg', 'Istanbul']

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/checkout@v1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node8-${{ hashFiles('**/package.json') }}

      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Run ${{ matrix.hardfork }} state tests
        run: npm run ${{ format('testState{0}', matrix.hardfork) }}
        env:
          CI: true

  test-blockchain:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hardfork: ['', 'Petersburg']

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/checkout@v1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node8-${{ hashFiles('**/package.json') }}

      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Run ${{ matrix.hardfork }} blockchain state tests
        run: npm run ${{ format('testBlockchain{0}', matrix.hardfork) }}
        env:
          CI: true
