name: block-coverage
'on':
  push:
    paths-ignore:
      - packages/account/**
      - packages/common/**
      - packages/tx/**
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npm install
        working-directory: '${{ env.cwd }}'
      - run: npm run coverage
        working-directory: '${{ env.cwd }}'
      - run: npm run coveralls
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/block'
