name: VM
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

defaults:
  run:
    working-directory: packages/vm

jobs:
  test-vm-state:
    # As having : in an Yaml string is so tricky, we're doing a partial string search using contains()

    if: contains(join(github.event.pull_request.labels.*.name, ' '), 'Test all hardforks')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fork: [
          'Berlin',
          'Istanbul',
        ]
      fail-fast: false
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: ${{ github.event.action }}
        continue-on-error: true

      - run: ${{ toJson(github) }}
        continue-on-error: true

      - run: ${{ toJson(github.event.pull_request.labels.*.name) }}
        continue-on-error: true
      
      - run: ${{ contains(github.event.pull_request.labels.*.name, 'Test all hardforks') }}
        continue-on-error: true
        name: Label check
      
      - run: ${{ matrix.fork }}
        continue-on-error: true

  test-vm-state-2:
    # if: contains(github.event.pull_request.labels.*.name, 'Test all hardforks')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fork: [
          'Berlin',
          'Istanbul',
        ]
      fail-fast: false
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: ${{ github.event.action }}
        continue-on-error: true

      - run: ${{ toJson(github) }}
        continue-on-error: true

      - run: ${{ toJson(github.event.pull_request.labels.*.name) }}
        continue-on-error: true
      
      - run: ${{ contains(join(github.event.pull_request.labels.*.name, ' '), 'Test all hardforks') }}
        continue-on-error: true
        name: Label check
      
      - run: ${{ contains(github.event.pull_request.labels.*.name, 'Test all hardforks') }}
        continue-on-error: true
        name: Label check
      
      - run: ${{ matrix.fork }}
        continue-on-error: true
