name: vm-nightly-test # without caching
on:
  schedule:
    - cron: '0 0 * * *' # once a day at midnight
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/checkout@v1

      - run: npm install

      - run: npm run testAPI
        env:
          CI: true

      - run: npm run testAPI:browser
        env:
          CI: true

  test-state:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hardfork: ['Byzantium', 'Constantinople', 'Petersburg', 'Istanbul']

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/checkout@v1

      - run: npm install

      - name: Run ${{ matrix.hardfork }} state tests
        run: npm run ${{ format('testState{0}', matrix.hardfork) }}
        env:
          CI: true

  test-blockchain:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hardfork: ['', 'Petersburg']

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/checkout@v1

      - run: npm install

      - name: Run ${{ matrix.hardfork }} blockchain state tests
        run: npm run ${{ format('testBlockchain{0}', matrix.hardfork) }}
        env:
          CI: true
