name: VM Test
'on':
  push:
    paths-ignore:
      - packages/account/**
      - packages/block/**
      - packages/blockchain/**
      - packages/common/**
      - packages/tx/**
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: '${{ runner.os }}-node8-${{ hashFiles(''**/package.json'') }}'
      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: '${{ env.cwd }}'
      - run: 'npm run test:API'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
      - run: 'npm run test:API:browser'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: '${{ runner.os }}-node8-${{ hashFiles(''**/package.json'') }}'
      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: '${{ env.cwd }}'
      - run: 'npm run test:state:selectedForks'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - uses: actions/checkout@v1
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: '${{ runner.os }}-node8-${{ hashFiles(''**/package.json'') }}'
      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: '${{ env.cwd }}'
      - run: 'npm run test:blockchain'
        env:
          CI: true
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
